### ISSUE TITLE
4.5.5 stable can't compile for Kakute F7 bdshot

### ISSUE THREAD

**Issue by brocciu** [ArduPilot/CustomBuild#101]
Here is the log :

"
../build_src/libraries/AP_RCTelemetry/AP_CRSF_Telem.cpp: In member function 'virtual bool AP_CRSF_Telem::init()':
../build_src/libraries/AP_RCTelemetry/AP_CRSF_Telem.cpp:71:13: error: 'vtx' is not a member of 'AP'
   71 |         AP::vtx().set_provider_enabled(AP_VideoTX::VTXType::CRSF);
      |             ^~~
compilation terminated due to -Wfatal-errors.

Waf: Leaving directory `/mnt/volume_nyc3_01/custom/base/tmp/copter:KakuteF7-bdshot:142aece2da56146d94dcad0f6b539af6960538f6:c951387ed8ac65d2dc2c38f0a01d5bc2/KakuteF7-bdshot'
Build failed
 -> task in 'objs/AP_RCTelemetry/ArduCopter' failed (exit status 1): 
	{task 139648992128560: cxx AP_CRSF_Telem.cpp -> AP_CRSF_Telem.cpp.3.o}
 (run with -v to display more information)
done build

BUILD_FINISHED
"

**Comment by andyp1per** [comment]
We build every release on all boards and this board is no exception. You must have an environment issue. I just built this with no issues.
