### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by twistedwings** [ArduPilot/CustomBuild#104]
https://custom.ardupilot.org/builds/copter:MatekF405:7ce11b4194f6c6b77d8e1f2bd5f14c0466d5e696:40e2a1838ac1b1486e25d6d48053a307/

**Comment by shiv-tyagi** [comment]
Can't see the log anymore. The logs don't persist sadly. They get deleted after 24 hours. Dump the log next time if you see this again.
