### ISSUE TITLE
Add TradHeli to drop-down list of vehicles

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/CustomBuild#33]
The "Choose a Vehicle" drop-down on the custom build server should include "TradHeli".  It should use the same branches as copter but needs to build with the frame type ("-f") set to "heli".

**Comment by bob-deruzhko** [comment]
Hello, is there any progress on this issue?

**Comment by Ryanf55** [comment]
It supports Heli; it's not called TradHeli. 

![image](https://github.com/ArduPilot/CustomBuild/assets/25047695/6ba75d6f-cfe2-4023-bdb9-4252eea2ff9e)

It was added in this commit: 

https://github.com/ArduPilot/CustomBuild/commit/0cca7de1d40f1d8ab8e7ff98231b342dd6958b94
