### ISSUE TITLE
Getting continously error message "Sending Unknown message (50)" on 4.3.0

### ISSUE THREAD

**Issue by Ltomi78** [ArduPilot/CustomBuild#39]
Issue details
I ve got information from Randy Mackay the reason is there is a coding error in this line in custom fw.
https://github.com/ArduPilot/ardupilot/blob/master/libraries/GCS_MAVLink/GCS_Common.cpp#L5752
the problem:
I upload 4.3.0 custom build fw https://custom.ardupilot.org/ and now getting this message continously:
"Sending Unknown message (50)"
Setup is: Fc matek f405 wing + gps and compass
Version
4.3.0 build with custom fw builder for matek f405 wing target

Platform
[ ] All
[ ] AntennaTracker
[ ] Copter
[X ] Plane
[ ] Rover
[ ] Submarine

Airframe type
flying wing

**Comment by Ltomi78** [comment]
![received_2193420617483978](https://user-images.githubusercontent.com/34459398/192499322-2904c734-5786-4c6a-ae1f-ee5a15a0a8d5.jpeg)

**Comment by isoos73** [comment]
Hi!

I also have this problem. Kakute F7 AIO, plane, 4.2 custom build. 

![50](https://user-images.githubusercontent.com/51860752/192532914-a5924960-92c9-4247-b73a-0dab87fdcb33.jpg)

**Comment by Hwurzburg** [comment]
would need to have the list of build options you used in order to recreate and diagnose....that line has nothing to do  with custom firmware itself...could be that you included adsb when you really dont have that hardware?

**Comment by isoos73** [comment]
I checked the "load" parameter in MP on status tab, it shows 4,1-4,4 values. I checked it on my Matek f405 Wing, it has the same values. If I understand correctly, it represents the load of fc's cpu. If it does not hangs the cpu, I do not care, but would be better not to have this annoying message. Thx!

**Comment by Hwurzburg** [comment]
I am on vacation this weeek and cant try myself...but will next week...

**Comment by Ltomi78** [comment]
> would need to have the list of build options you used in order to recreate and diagnose....that line has nothing to do with custom firmware itself...could be that you included adsb when you really dont have that hardware?

Hi.
I ve also not included adsb but here is my build log about option i ve selected.
After i tried also with much less option but also got this unknown message
![20220926_234438](https://user-images.githubusercontent.com/34459398/192601126-6925e7cc-6b3a-4059-9888-29ee00f4fdf1.jpg)

**Comment by Ltomi78** [comment]
> I am on vacation this weeek and cant try myself...but will next week...

Thanks for your time..waiting your reply

**Comment by Hwurzburg** [comment]
figured out the error and asked dev responsible for it to fix it

**Comment by Hwurzburg** [comment]
this has been fixed...try again

**Comment by Ltomi78** [comment]
> this has been fixed...try again

Thank you..for your fast feedback and work..we will check it

**Comment by Ltomi78** [comment]
> this has been fixed...try again

All work as it should thank you very much
![Uploading Screenshot_20221001-220206_Messenger.jpg…]()
