### ISSUE TITLE
Pixracer -bdshot custom build not possible without Compass 'HMC5843'

### ISSUE THREAD

**Issue by Janno117** [ArduPilot/CustomBuild#59]
Custom firmware build for Pixracer -bdshot fails, if compass 'HMC5843' is not enabled.

For more information see https://custom.ardupilot.org/builds/copter:Pixracer-bdshot:d40320b1c2a72e585d942a97e0134944e54c1118:7d6bc721e2232890393184c348c66f1f/ .

The files 'build.log', 'extra_hwdef.dat' and 'selected_features.json' are also included in the zip-file below.
[build_details.zip](https://github.com/ArduPilot/CustomBuild/files/12513042/build_details.zip)

**Comment by Hwurzburg** [comment]
because that device is integrated onboard and must have a driver since its spec'd in the hwdef
