### ISSUE TITLE
Speedybee F405 Wing missing in custom builder

### ISSUE THREAD

**Issue by ojoojoo** [ArduPilot/CustomBuild#67]
Hello,

The Speedybee F405 Wing is missing in the custom builder, is this to be added in the future please?

Regards,

Orson

**Comment by Hwurzburg** [comment]
no its there![Screenshot from 2023-12-23 15-33-48](https://github.com/ArduPilot/CustomBuild/assets/6076534/91fb115d-bd3e-4b61-9310-d7b62a491a3f)

**Comment by ojoojoo** [comment]
My bad, sorry

Op 23 dec 2023 om 22:34 heeft Henry Wurzburg ***@***.***> het volgende geschreven:

﻿

no its thereScreenshot.from.2023-12-23.15-33-48.png (view on web)<https://github.com/ArduPilot/CustomBuild/assets/6076534/91fb115d-bd3e-4b61-9310-d7b62a491a3f>
