### ISSUE TITLE
Add HAL_BUTTON_ENABLED to the list of available features to enable/disable

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/CustomBuild#68]
It looks like we've disabled AP_Button from some builds to save flash so we should add this as an option to re-enable via the custom build server.

This request comes from this discussion https://discuss.ardupilot.org/t/missing-gpio-button-btn-enable-on-f405-fcs/111802

**Comment by Hwurzburg** [comment]
#26022 https://github.com/ArduPilot/ardupilot/pull/26022
