### ISSUE TITLE
Available features Other to AHRS and Safety

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/CustomBuild#75]
I think we should move these items that are currently in the "Other" section:

- "Advanced Failsafe Features" should move to "Safety"
- "Baro Wind Compensation" should move to "AHRS"
- "I2C Displays" should move to "Notify"

**Comment by Hwurzburg** [comment]
this will need just a change to build_options.py     will do it in a couple of days, if not sooner

**Comment by Hwurzburg** [comment]
see https://github.com/ArduPilot/ardupilot/pull/26656

**Comment by shiv-tyagi** [comment]
Adressed by [ArduPilot/ardupilot#26656](https://github.com/ArduPilot/ardupilot/pull/26656). Thanks @Hwurzburg.

**Comment by rmackay9** [comment]
Thanks!
