### ISSUE TITLE
Select branch should include "Copter 4.5 stable"

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/CustomBuild#76]
We've just released Copter-4.5.0 as the stable version for Copter, Rover, Plane and Tracker but it doesn't look like it's shown up in the custom build server.  Maybe there is some meta data somewhere that we need update?

**Comment by shiv-tyagi** [comment]
Hey @rmackay9! Yeah, I am trying to automate this. For now,  I'll do a PR to manually update the list.

**Comment by shiv-tyagi** [comment]
Closed by #77
